POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
    "username": "admin",
    "password": "760412",
    "role": "ADMINISTRATOR"
}
    // {
    //     "email": "

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username": "admin",
    "password": "760412"
}


###
GET http://localhost:5000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWI3MDVlOGM1ZWZmN2ZkODA3YjQiLCJpYXQiOjE2NDc0Mzg4MDZ9.AoLMUJlzFwMLJdZ3Gkmp7V-z6fUr3YXCmuENlAZ8358

###
GET http://localhost:5000/api/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxYzY4NmU3YTBjNWM5YTk3ZjdiNDgiLCJpYXQiOjE2NDg0Nzc4NzF9.v_gxLBXCSnZQLJxWlkq0qPe3T3q3QhH-dGwS7st72LAq


###
POST http://localhost:5000/api/lines
Content-Type: application/json


{
    "lineNumber": 21,
    "description": "line1",
    "status": true,
    "user":"6231ebaa5e8c5eff7fd807ba"
}


###
GET http://localhost:5000/api/lines/getlinebyuser 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWJhYTVlOGM1ZWZmN2ZkODA3YmEiLCJpYXQiOjE2NDc0Mzk5Mjl9.-rsoF_uUe_hLW46VfUK7Hx35Jn_YuW68tIXQ-junI7A

###
GET http://localhost:5000/api/lines


###
GET http://localhost:5000/api/transporters/getbyline/6232114cf7a0ffd6a4caabbb
