POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
    "username": "nhanvien3",
    "name": "Thuận Anh",
    "password": "123456",
    "role": "OPERATOR"
}
    // {
    //     "email": "

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username": "admin",
    "password": "123456"
}


###
GET http://localhost:5000/api/auth/getOperatorLine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQzY2Q4MmM2M2NiNzliMzk2NTQ1ZGYiLCJpYXQiOjE2NDg2MTM3NjB9.RaTnLaEv16pCJ-8BPAP_XjHomVQCUipONz9VzQ9WAoc

###
GET http://localhost:5000/api/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQxYzY4NmU3YTBjNWM5YTk3ZjdiNDgiLCJpYXQiOjE2NDg0Nzc4NzF9.v_gxLBXCSnZQLJxWlkq0qPe3T3q3QhH-dGwS7st72LAq
###
GET http://localhost:5000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQzY2Q4MmM2M2NiNzliMzk2NTQ1ZGYiLCJpYXQiOjE2NDg2MTM3NjB9.RaTnLaEv16pCJ-8BPAP_XjHomVQCUipONz9VzQ9WAoc

###
POST http://localhost:5000/api/lines
Content-Type: application/json


{
    "lineNumber": "011",
    "description": "Tuyến vũng tàu",
    "status": true
   
}
###
POST http://localhost:5000/api/lines/assignUser
Content-Type: application/json


{
    "userId": "6243d695c63cb79b39654622",
    "lineId": "6243f9557f0fa01c27807f62"
}


###
GET http://localhost:5000/api/lines/getLineByKeyword/21


###
GET http://localhost:5000/api/lines/getlinebyuser 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjMxZWJhYTVlOGM1ZWZmN2ZkODA3YmEiLCJpYXQiOjE2NDc0Mzk5Mjl9.-rsoF_uUe_hLW46VfUK7Hx35Jn_YuW68tIXQ-junI7A

###
GET http://localhost:5000/api/lines


###
GET http://localhost:5000/api/transporters/getbyline/6232114cf7a0ffd6a4caabbb


###
GET http://localhost:5000/api/units



###
POST http://localhost:5000/api/units
Content-Type: application/json

{
    "name":"Bảo Yến"
}


###
GET http://localhost:5000/api/units/getAllUnitLine


###
POST http://localhost:5000/api/units/assignLine
Content-Type: application/json

{
    "unitId":"624477ec811bf62af3b7cd32",
    "lineId":"6241d6ec1ab53254da85fdeb"
}

###
GET http://localhost:5000/api/dashboard/getQualityByUnit

###
GET http://localhost:5000/api/dashboard/getQualityUnitMonth/3/2022

###
GET http://localhost:5000/api/transporters/

###
GET http://localhost:5000/api/transporters/getBusByKeyword/50

###
GET http://localhost:5000/api/dashboard/getQualityTransporterBydate/624584bd88579d6dbb71f467/2021-01-01/2022-03-31


###
GET http://localhost:5000/api/dashboard/getQualityLineBydate/6241d6ec1ab53254da85fdeb/2021-01-01/2022-03-31

###
GET http://localhost:5000/api/dashboard/getQualityUnitBydate/624477f3811bf62af3b7cd35/2021-01-01/2022-04-17